language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra
  - add-on
script:
- "./gradlew assembleRelease"
- jarsigner -verbose -sigalg SHA1withRSA -storepass $storepass -keypass $keypass -digestalg
  SHA1 -keystore android.jks app/build/outputs/apk/app-release-unsigned.apk fastlanetraviscipoc
- "/usr/local/android-sdk/build-tools/23.0.3/zipalign -v 4 app/build/outputs/apk/app-release-unsigned.apk
  app/build/outputs/apk/app-release.apk"
- ls -la app/build/outputs/apk
- supply -v
- supply run -j gpdpapi.service_account.json -p tgd.mindless.drone.fastlanetravis_ciproofofconcept -b app/build/outputs/apk/app-release.apk
before_install:
- openssl aes-256-cbc -K $encrypted_ac5b2a59fcae_key -iv $encrypted_ac5b2a59fcae_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- rvm install 2.3.1
- gem install supply
