language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra
  - add-on
script: ./build.sh
before_install:
- openssl aes-256-cbc -K $encrypted_ac5b2a59fcae_key -iv $encrypted_ac5b2a59fcae_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- rvm install 2.3.1
- gem install supply
