language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra
  - add-on
script:
- "./gradlew assembleRelease"
- jarsigner -verbose -sigalg SHA1withRSA -storepass $storepass -keypass $keypass -digestalg SHA1 -keystore android.jks app/build/outputs/apk/app-release-unsigned.apk fastlanetraviscipoc
- zipalign -v 4 app/build/outputs/apk/app-release-unsigned.apk app/build/outputs/apk/app-release.apk
- ls -la app/build/outputs/apk
before_install:
- openssl aes-256-cbc -K $encrypted_ac5b2a59fcae_key -iv $encrypted_ac5b2a59fcae_iv
  -in android.jks.enc -out android.jks -d
